### ISSUE TITLE
README.md Mentions wound down dev mailing list

### ISSUE THREAD

**Issue by reflektoin** [racket/string-constants#59]
The README mentions "joining the [development mailing list](https://lists.racket-lang.org/)" which has been wound down: [link](https://groups.google.com/g/racket-dev/c/p5Vo74sadTo).

Maybe the mailing list could be changed to point to [Racket Discourse Group](https://racket.discourse.group/)?

**Comment by samth** [comment]
I think we should change lists.racket-lang.org to point there.

**Comment by rfindler** [comment]
Hope this is a reasonable change. Let me know if something else would be better and thanks for the report!
